import {
  DocumentData,
  FieldValue,
  QueryDocumentSnapshot,
} from "firebase/firestore";

/**
 * Heist document as read from Firestore (after conversion)
 * Represents a workplace "heist" (task/challenge) that users create and complete
 */
export interface Heist {
  id: string;
  title: string;
  description: string;
  createdBy: string; // User UID who created the heist
  createdByCodename: string; // Codename/display name of the creator
  assignedTo: string; // User UID assigned to complete the heist
  assignedToCodename: string; // Codename/display name of assignee
  deadline: Date; // 48 hours from creation
  finalStatus: null | "success" | "failure"; // Null until completion
  createdAt: Date; // Timestamp when heist was created
}

/**
 * Input type for creating a new heist via addDoc
 * Excludes id (auto-generated by Firestore)
 */
export interface CreateHeistInput {
  title: string;
  description: string;
  createdBy: string;
  createdByCodename: string;
  assignedTo: string;
  assignedToCodename: string;
  deadline: Date; // Caller should calculate as 48 hours from now
  finalStatus: null; // Always starts as null
  createdAt: FieldValue; // serverTimestamp()
}

/**
 * Input type for updating an existing heist via updateDoc
 * All fields are optional, and createdAt/id are excluded
 */
export interface UpdateHeistInput {
  title?: string;
  description?: string;
  assignedTo?: string;
  assignedToCodename?: string;
  deadline?: Date;
  finalStatus?: null | "success" | "failure";
}

/**
 * Firestore converter for heist documents
 * Handles serialization (toFirestore) and deserialization (fromFirestore)
 * Converts Timestamp fields to Date objects
 */
export const heistConverter = {
  toFirestore: (data: Partial<Heist>): DocumentData => data,

  fromFirestore: (snapshot: QueryDocumentSnapshot): Heist => {
    const data = snapshot.data();
    return {
      id: snapshot.id,
      title: data.title,
      description: data.description,
      createdBy: data.createdBy,
      createdByCodename: data.createdByCodename,
      assignedTo: data.assignedTo,
      assignedToCodename: data.assignedToCodename,
      deadline: data.deadline?.toDate?.() || data.deadline,
      finalStatus: data.finalStatus,
      createdAt: data.createdAt?.toDate?.() || data.createdAt,
    } as Heist;
  },
};
